name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

# env:
#   TF_CLOUD_ORGANIZATION: "testing-workspaces"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
#   WORKING_DIRECTORY: "./"

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@15ebb9c5dc0bc134cfdbd4cc58b031fafe651e7f
    with:
      env: dev
      TF_CLOUD_ORGANIZATION: "testing-workspaces"
      TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
      WORKING_DIRECTORY: "./"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
