name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - Terraform Run:
        uses: ekbrothers/tfc-api-driven-reusable-workflow/blob/main/.github/workflows/tfc-api-driven-reusable-workflow@dbd6baf1e33e15e9d072cb66c21011dc1df2ceec
        with:
          TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
          TF_API_TOKEN: ${{ secrets.TESTING_TOKEN }}
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
          CONFIG_DIRECTORY: "./test_directory"
