name: Terraform Plan on Push to Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/ru-tfc-api-driven.yaml@c17e2ab9486771f5ac156e84fc7ed657785acd80
    with:
      ENV: dev
      TF_CLOUD_ORGANIZATION: "testing-workspaces"
      TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
      WORKING_DIRECTORY: "./"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
