name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@339b174243abb3d87e6ffc304097a73eb18ed42d
    with:
      TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TESTING_TOKEN }}
      TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
      CONFIG_DIRECTORY: "./test_directory"
