name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

# env:
#   TF_CLOUD_ORGANIZATION: "testing-workspaces"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
#   WORKING_DIRECTORY: "./"

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@a39492c5eaa1ccbca18369a1de2b83b709941487
    with:
      env: dev
      TF_CLOUD_ORGANIZATION: "testing-workspaces"
      TF_API_TOKEN: "06VyGwznfwewVA.atlasv1.vEqEhDklpK9fkMrCKht5IZhehPY0ThtueSU5jTAken8LRSPmUzqP72lr4wZYwzJ8OYM"
      TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
      WORKING_DIRECTORY: "./"
    # secrets:
    #   TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
