name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "testing-workspaces"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
  WORKING_DIRECTORY: "./"

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    runs-on: ubuntu-latest
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@853bb452b51fed652aa933ea3405d6e59a2811d8
    with:
      env: dev
    # secrets:
    #   TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
