```yaml
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: ekbrothers/tfc-api-drive-reusable-workflow@v1.0
        with:
          TF_CLOUD_ORGANIZATION: 'YOUR-ORGANIZATION-HERE'
          TF_API_TOKEN: ${{ secrets.TESTING_TOKEN }}
          TF_WORKSPACE: 'your-workspace'
          CONFIG_DIRECTORY: './test_directory'