name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@03662e7c0604f489e0fd43d16a7d7abc3003af72
    with:
      env: dev
      TF_CLOUD_ORGANIZATION: testing-workspaces
      TF_WORKSPACE: tfc-api-driven-reusable-workflow
      WORKING_DIRECTORY: "./test_directory"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
