name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     tfchoice:
  #       type: choice
  #       description: Choose Plan, Apply, or Destroy
  #       options:
  #       - Plan
  #       - Apply
  #       - Destroy

jobs:
  # set-matrix:
  #   name: set variables
  #   runs-on: ubuntu-latest
    # outputs:
    #   decision_matrix: ${{ steps.matrix-output.outputs.decision-matrix }}
    # steps:
    #   - name: apply values
    #     run: |
    #       if [ "${{ inputs.tfchoice }}" == "Plan" ] || [ ${{ github.event_name }} == "pull_request" ]; then
    #         decision='[ {"apply": false, "destroy": false, "plan": true } ]';
    #       elif [ "${{ inputs.tfchoice }}" == "Apply" ] || [ ${{ github.event_name }} == "push" ]; then
    #         decision='[ {"apply": true, "destroy": false, "plan": false } ]';
    #       elif [ "${{inputs.tfchoice}}" == "Destroy" ]; then
    #         decision='[ {"apply": false, "destroy": true, "plan": false } ]';
    #       fi
    #       echo "decision-matrix=$decision" >> $GITHUB_OUTPUT
    #     id: matrix-output
    #     shell: bash
  terraform-plan:
    name: Dev Provisioning - Demo
    # needs: set-matrix
    # strategy:
    #   matrix:
    #     tf-choice: ${{fromJSON(needs.set-matrix.outputs.decision_matrix)}}
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/ru-tfc-api-driven.yaml@4663e5a7abc108ae4eb6eeb147eac914e3ba8efc
    with:
      ENV: dev
      # TF-PLAN: ${{matrix.tf-choice.plan}}
      # TF-APPLY: ${{matrix.tf-choice.apply}}
      # TF-DESTROY: ${{matrix.tf-choice.destroy}}
      TF_CLOUD_ORGANIZATION: "testing-workspaces"
      TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
      WORKING_DIRECTORY: "./"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
