name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@6a21de81f326411302a8dc5c7746e7115ae0fdd8
    with:
      TF_CLOUD_ORGANIZATION: testing-workspaces
      TF_WORKSPACE: tfc-api-driven-reusable-workflow
      WORKING_DIRECTORY: "./test_directory"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
