name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Terraform Run
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@1cf56f278c944bd4c0169686761b3ebdf1f94891
    with:
      TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TESTING_TOKEN }}
      TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
      CONFIG_DIRECTORY: "./test_directory"
