name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: ekbrothers/tfc-api-driven-reusable-workflow@v1.0
        with:
          TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
          TF_API_TOKEN: ${{ secrets.TESTING_TOKEN }}
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
          CONFIG_DIRECTORY: "./test_directory"
