name: Terraform Plan on Push to Main

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "testing-workspaces"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "tfc-api-driven-reusable-workflow"
  WORKING_DIRECTORY: "./"

jobs:
  terraform-plan:
    name: Dev Provisioning - Demo
    uses: ekbrothers/tfc-api-driven-reusable-workflow/.github/workflows/tfc-api-driven-reusable-workflow.yaml@dc9ae048c5319a726b60c3b31187d38ec9cada73
    with:
      env: dev
    # secrets:
    #   TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
